#!/bin/bash
clear

echo "========================================================"
echo "   ██████  ██░ ██  ▄▄▄      ▓█████▄  ▒█████   █     █░  " 
echo " ▒██    ▒ ▓██░ ██▒▒████▄    ▒██▀ ██▌▒██▒  ██▒▓█░ █ ░█░"
echo " ░ ▓██▄   ▒██▀▀██░▒██  ▀█▄  ░██   █▌▒██░  ██▒▒█░ █ ░█   "
echo "   ▒   ██▒░▓█ ░██ ░██▄▄▄▄██ ░▓█▄   ▌▒██   ██░░█░ █ ░█   "
echo " ▒██████▒▒░▓█▒░██▓ ▓█   ▓██▒░▒████▓ ░ ████▓▒░░░██▒██▓   "
echo " ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒ ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░▒░▒░ ░ ▓░▒ ▒    "
echo " ░ ░▒  ░ ░ ▒ ░▒░ ░  ▒   ▒▒ ░ ░ ▒  ▒   ░ ▒ ▒░   ▒ ░ ░    "
echo " ░  ░  ░   ░  ░░ ░  ░   ▒    ░ ░  ░ ░ ░ ░ ▒    ░   ░    "
echo "       ░   ░  ░  ░      ░  ░   ░        ░ ░      ░      "
echo "                           ░                            "
echo "               ____         __       ____               "  
echo "              /  _/__  ___ / /____ _/ / /               "
echo "             _/ // _ \(_-</ __/ _ '/ / /                "
echo "            /___/_//_/___/\__/\_'_/_/_/                 "
echo "                                                        "
echo "====================MADE BY URUSAY======================"
echo "	     !==========================!                "
echo "	     !	     Options	        !                "
echo "	     !1.Instalar irssi 	        !                "
echo "	     !2.Instalar theHarvester   !                "
echo "	     !3.Instalar p0f	        !                "
echo "	     !4.Instalar iceweasel      !                "
echo "	     !5.Instalar tor	        !                "
echo "	     !6.Instalar torbrowser     !                "
echo "	     !7.Instalar java	        !                "
echo "	     !8.Instalar whatweb	!                "
echo "	     !9.Instalar dmitry	        !                "
echo "	     !10.Instalar netdiscover   !	         "
echo "	     !11.Instalar wine	        !	         "
echo "	     !3.Instalar Shadow 2.0     !                "
echo "	     !==========================!		 "

echo " Inserte el numero: " 

read op

clear
if [ "$op" = "1" ];
 then apt install irssi && shadowinstaller
elif [ "$op" = "2" ]; then
 apt install theHarvester  && shadowinstaller
elif [ "$op" = "3" ]; then
 apt install p0f && shadowinstaller
elif [ "$op" = "4" ]; then
 apt install iceweasel && shadowinstaller
elif [ "$op" = "5" ]; then
 apt install tor  && shadowinstaller
elif [ "$op" = "6" ]; then
 apt install torbrowser-launcher  && shadowinstaller
elif [ "$op" = "7" ]; then
 apt install javacc && shadowinstaller
elif [ "$op" = "8" ]; then
  apt install whatweb  && shadowinstaller
elif [ "$op" = "9" ]; then
 apt install dmitry && shadowinstaller
elif [ "$op" = "10" ]; then
 apt install netdiscover && shadowinstaller
elif [ "$op" = "11" ]; then
 sudo dpkg --add-architecture i386 && wget -nc https://dl.winehq.org/wine-builds/winehq.key && sudo apt-key add winehq.key && echo "agregar estos repositorios deb https://dl.winehq.org/wine-builds/debian/ stretch main, deb https://dl.winehq.org/wine-builds/debian/ buster main, deb https://dl.winehq.org/wine-builds/debian/ bullseye main"
elif [ "$op" = "12" ]; then
 sudo apt update && sudo apt install --install-recommends winehq-stable
elif  [ "$op" = "13" ]; then
 git clone
fi

